apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-managed-csi
spec:
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
