apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-file-csi
spec:
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
